Intro section
totfront/somewhere-travel pull request #9
Opened 2022-12-03 12:33 UTC by LalightKosh

This is a branch with "intro" section changes from [this PR](https://github.com/totfront/somewhere-travel/pull/5)

2022-12-03 15:36 UTC, totfront commented on src/components/Lead/Lead.js
> +        <figcaption className={styles.caption}>ваша полка - верхняя</figcaption>
According to the prototype there should be "—"

2022-12-03 15:43 UTC, totfront requested changes
The review is rejected:

1. There are conflicts with the main branch that should be resolved
2. Only mobile prototype has been implemented, but not the rest

Please, fix those two and request again

2022-12-08 19:49 UTC, totfront approved these changes

2022-12-11 11:00 UTC, totfront commented
Please always check if the build is fine. This is critically important.
![image](https://user-images.githubusercontent.com/42805085/206899786-2744ce71-e557-4679-bf38-48bc900e120f.png)

2022-12-11 11:36 UTC, totfront commented
Nice and clean PR. That was a pleasure to check it. Good work with media queries and good-looking small CSS files.

Design inconcistancies:
1. Space before "часовых поясов" should be 34px. You have not explicitly set it and not it is occasionally made of 2 margins 16px + 16px.

I would like you to fix all of my suggestions, but they are slightly out of the requirements except the one with the design. Fix it and I will aprove.

2022-12-11 12:39 UTC, LalightKosh commented
> Please always check if the build is fine. This is critically important. ![image](https://user-images.githubusercontent.com/42805085/206899786-2744ce71-e557-4679-bf38-48bc900e120f.png)

It is working for me

2022-12-11 12:41 UTC, LalightKosh commented
> Nice and clean PR. That was a pleasure to check it. Good work with media queries and good-looking small CSS files.
> 
> Design inconcistancies:
> 
> 1. Space before "часовых поясов" should be 34px. You have not explicitly set it and not it is occasionally made of 2 margins 16px + 16px.
> 
> I would like you to fix all of my suggestions, but they are slightly out of the requirements except the one with the design. Fix it and I will aprove.

done.

2022-12-16 17:41 UTC, totfront commented
The issue is this there. Please, fix it

2022-12-16 21:34 UTC, LalightKosh commented
> 

I fixed margins.

2022-12-19 18:37 UTC, totfront approved these changes

2023-01-04 18:47 UTC, LalightKosh commented on src/components/Intro/Intro.js
> +      <title className={styles.title}>Чего мы там не видели?</title>
changed. I have changed it everywhere already, but forgot about Intro.

2023-01-04 18:48 UTC, LalightKosh commented on src/components/Intro/Intro.js
> +          12
I have changed this on a different branch and merged. :/ sorry, got my lesson.

2023-01-04 18:51 UTC, LalightKosh commented on src/components/Intro/Intro.module.css
> +        align-items: start;
you are correct. I have removed flex.

2023-01-04 18:51 UTC, LalightKosh commented on src/components/Intro/Intro.module.css
> +    margin-left: 34px;
fixed

2023-01-04 18:54 UTC, merged